
version: '3.7'
networks:
  internal:
    driver: bridge

services:
  steamcmd:
    image: win_steamcmd
    hostname: SteamCMD
    container_name: ark_asa
    restart: unless-stopped
    networks:
      - internal
    dns:
      - 1.1.1.1
      - 1.0.0.1
      - 8.8.8.8
      - 8.8.4.4

    environment:
      TZ: America/Chicago
      #GAME_ID can be found at: xxxxxxxxxx
      GAME_ID: 2430930
      #GAME_NAME has to be exact for correct folder structure
      GAME_NAME: "ARK Survival Ascended Dedicated Server"
      GAME_LOG: "/ShooterGame/Saved/Logs/ShooterGame.log"
      GAME_EXE: "/ShooterGame/Binaries/Win64/ArkAscendedServer.exe"
      GAME_ARG: "TheIsland_WP?listen??ServerAdminPassword=GT? -WinLiveMaxPlayers=5 -clusterid=cluster -servergamelog -servergamelogincludetribelogs -ServerRCONOutputTribeLogs -NotifyAdminCommandsInChat -nosteamclient"


    ports:
      # - "7777:7777/tcp"
      - "7777:7777/udp"
      # - "27015:27015/tcp"
      # - "27015:27015/udp"
      # - "27016:27016/tcp"
      # - "27016:27016/udp"

    volumes:
      - "/data/steam2:/usr/games/.wine/drive_c/Steam/steamapps/common"
      # If GAME_ARG is not enought to configure your server
      # you can map the config files directly into the Docker 
      #
      #- "./GameUserSettings.ini:/usr/games/.wine/drive_c/Steam/steamapps/common/ARK Survival Ascended Dedicated Server/ShooterGame/Saved/Config/WindowsServer/GameUserSettings.ini"
      #- "./Game.ini:/usr/games/.wine/drive_c/Steam/steamapps/common/ARK Survival Ascended Dedicated Server/ShooterGame/Saved/Config/WindowsServer/Game.ini"
    mem_limit: 24G
